imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: symforce/config.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator: 
        fallback: %locale%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: %sf.version%
        version_format: '%%s?version=%%s'
        base_path: %sf.web_assets_dir%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        web_assets_dir: %sf.web_assets_dir%
    
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: %assetic.use_controller%
    read_from:      %kernel.root_dir%/../web%sf.web_assets_dir%
    write_to:       %kernel.root_dir%/../web%sf.web_assets_dir%
    bundles:        %assetic.bundles%
    java: %assetic.java_path%
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        #less:
        #    node: %assetic.node_path%
        #    node_paths: %assetic.node_paths%
        #    apply_to: "\.less$"
        closure:
            jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            uuid: Symforce\AdminBundle\Doctrine\DBAL\Types\UuidType
        # blob: Symforce\AdminBundle\Doctrine\DBAL\Types\BlobType 
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port : %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    # auth_mode: %mailer_auth_mode%
    # spool:     { type: memory }
