
#_sf_user_fos:
#    resource: "@SymforceUserBundle/Resources/config/routing/fos.yml"
    
#_sf_group_fos:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /group 

#_fos_comment_api:
#    type: rest
#    resource: "@FOSCommentBundle/Resources/config/routing.yml"
#    prefix: /user/comment
#    defaults: { _format: html }
    
_sf_admin:
    resource: "@SymforceAdminBundle/Resources/config/routing.yml"
