_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   %sf.web_assets_dir%/_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   %sf.web_assets_dir%/_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   %sf.web_assets_dir%/_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:    %sf.web_assets_dir%/_error

_assetic:
    resource: .
    type: assetic
    prefix: '%sf.web_assets_dir%'

#_sf_fos_message:
#    resource: "@FOSMessageBundle/Resources/config/routing.xml"
#    prefix: /message

_main:
    resource: routing.yml
