_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   %app.web_assets_dir%/_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   %app.web_assets_dir%/_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   %app.web_assets_dir%/_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:    %app.web_assets_dir%/_error

_assetic:
    resource: .
    type: assetic
    prefix: '%app.web_assets_dir%'

_app_fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

_main:
    resource: routing.yml
