
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        
    acl:
        connection: default
        
    role_hierarchy:
        ROLE_MEMBER: ROLE_USER
        ROLE_ADMIN: ROLE_MEMBER
        ROLE_ADMIN_EDITOR: ROLE_ADMIN
        ROLE_ADMIN_MANAGER: ROLE_ADMIN
        ROLE_ADMIN_PARTNER: ROLE_ADMIN
        ROLE_ADMIN_BOSS: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ ROLE_USER , ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^%sf.web_assets_dir%/
            security: false

        login:
            pattern:  ^%sf.web_admin_dir%/login$
            security: false
        
        secured_area:
            pattern:    ^%sf.web_admin_dir%/
            form_login:
                # always_use_default_target_path: true
                default_target_path: sf_admin_dashboard
                check_path: sf_admin_check
                login_path: sf_admin_login
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                
                # csrf_parameter: form[_token1]
                # intention:      authenticate
                # csrf_provider: form.csrf_provider
                
                # by default, the login form *must* be a POST, not a GET
                post_only:      true
                remember_me:    false

            logout:
                path:   sf_admin_logout
                target: sf_admin_dashboard

        main:
            pattern: ^%sf.web_root_dir%/
            form_login:
                provider:       fos_userbundle
                login_path:     %sf.web_root_dir%/login
                use_forward:    false
                check_path:     %sf.web_root_dir%/login_check
                # success_handler: ccdn_user_security.component.authentication.handler.login_success_handler
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                failure_path:   null
                post_only:      true
                remember_me:    true
                #failure_handler: sf.user.ajax_handler
                #success_handler: sf.user.ajax_handler

            logout:
                path:   %sf.web_root_dir%/logout
                target: %sf.web_root_dir%
                # success_handler: ccdn_user_security.component.authentication.handler.logout_success_handler
            anonymous:  true
            
    access_control:
        - { path: ^%sf.web_assets_dir%/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^%sf.web_root_dir%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%sf.web_root_dir%/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%sf.web_root_dir%/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^%sf.web_admin_dir%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%sf.web_admin_dir%/, role: ROLE_ADMIN }
