
parameters:
    mopa_bootstrap.form.templating: "SymforceAdminBundle:Form:fields.html.twig"
    sf_routing.default_template: "AppWebBundle::page_entity.html.twig"

sf_admin:
    language:
        en: English
        zh_CN: 简体中文

    form:
        type:
            authorize: Symforce\UserBundle\Form\MetaType\AuthorizeMetaType

    admin:
        menu:
            groups:
                # sys: { label: "Base Menu", icon:"flag" }
                admin_group: { label: "System Menu", icon:"flag" }
                  # home: { parent:sys, label:"Home", icon:"star" , divider:false, route:"_cmf_home" }

        dashboard:
            groups:
                default: { label: "#", right_side:false }
                right: { label: "#", right_side:true }
                public: { label: "#", right_side:true }
