imports:
    - { resource: admin.yml }
    - { resource: ../knp/knp_paginator.yml }
    # - { resource: ../fos/fos_user.yml }
    # - { resource: ../fos/fos_message.yml }
    # - { resource: ../fos/fos_comment.yml }
    # - { resource: ../cmf/cmf_routing.yml }
    - { resource: stof.yml }
    - { resource: mopa.yml }
    # - { resource: jms_di.yml }
    
parameters:
    security.authentication.listener.form.class: Symforce\UserBundle\Listener\UserLoginFormListener

gregwar_captcha:
    width: 120
    height: 40
    length: 5
    # quality: 90
    as_url: true 
    reload: true 
    keep_value: false 
    expiration: 60