# app/config/knp/menu.yml

knp_menu:
    twig:
        template: "SymforceAdminBundle:Menu:menu_bootstrap.html.twig"
    templating: false # if true, enables the helper for PHP templates
    default_renderer: bootstrap # The renderer to use, list is also available by default